### ISSUE TITLE
Animation template 

### ISSUE THREAD

**Issue by tkusma** [no-slopes/sprite-animations#2]
I have several sprite sheets with the same animation for different characters. It would be interesting to have a feature where I can create an animation template that will be common to several prefabs, and I only need to change the list of sprites for each of them.

Any solution for this situation will be greatly appreciated, and I thank you in advance!

**Comment by indiegabo** [comment]
Hey @tkusma ! Thanks for your suggestion. I'll have a look into that this week! 

I'll let you know when it gets released.

**Comment by indiegabo** [comment]
Hey @tkusma! This has been implemented at [v2.1.0](https://github.com/no-slopes/sprite-animations/releases/tag/v2.1.0) . 

Thanks for helping me make the tool better. Docs are yet to come but you can already check samples on how to use it!
