### ISSUE TITLE
Unnecessary namespace using in SpriteAnimationComposite.cs:4

### ISSUE THREAD

**Issue by li5414** [no-slopes/sprite-animations#3]
Please remove the unnecessary namespace `using Codice.Client.BaseCommands.Download;` in `SpriteAnimationComposite.cs:4`

**Comment by indiegabo** [comment]
Hey @li5414 ! Sorry about the delayed reponse.

This has been just taken care off in [v2.3.2](https://github.com/no-slopes/sprite-animations/releases/tag/v2.3.2). Let me know if everything is ok then I'll close the issue. I was trying to solve a building issue and came across this miss import. No idea how it got there. 

Thanks for using the tool and helping me make it better.

**Comment by li5414** [comment]
it‘s ok nownow I can try using it

**Comment by indiegabo** [comment]
Closing this. Let me know if any other buggy stuff attack you.
