### ISSUE TITLE
Context menu in Unity 2023

### ISSUE THREAD

**Issue by arttmptt** [no-slopes/sprite-animations#4]
**Describe the bug**
Can't choose type of animation in Unity 2023 when creating one. Window of creation is disappearing, can't create animation from the Sprite Animator window.
This bug seems to come with the new context menu in Unity 2023+.
In Unity 2022 LTS, everything was fine.

**To Reproduce**
1. Click on green Create button, open Create Animation window
2. Click on Type selection
3. Window of creation is disappeared

**Expected behavior**
Window shouldn't disappear.

**Screenshots**
![image](https://github.com/no-slopes/sprite-animations/assets/38746516/3922bddc-206a-4759-aa5a-6bc4a3953a9c)
![image](https://github.com/no-slopes/sprite-animations/assets/38746516/db692a39-8919-425b-89cc-813255372d1d)

 - OS: Windows 11 64 bit
 - Plugin Version 2.3.3

**Comment by indiegabo** [comment]
Hey @arttmptt ! Thanks for reporting this. 

Sorry about the delayed reponse on this. It has been some busy weeks.

I'll take a look into it.

**Comment by indiegabo** [comment]
Hey @arttmptt . Wich exact version of 2023 are you experiencing this behaviour? 

Just checked out in 2023.1.16f1 and the window is not dissapearing.

![image](https://github.com/no-slopes/sprite-animations/assets/95456621/ca70d1be-9ed5-4d5d-a4bc-31c92c1de4f8)

Been getting this annoying warnings though:

![image](https://github.com/no-slopes/sprite-animations/assets/95456621/f660821a-11b9-461d-89e4-2ce259b1a134)

I'll try and get rid of those while I wait for your response about the exact Unity version.

**Comment by indiegabo** [comment]
Been Able to reproduce under Unity 2023.2.16f1 .

**Comment by arttmptt** [comment]
Hey @indiegabo ! Got this issue in Unity 2023.2.13f1 and tested in 2023.2.16f1, still exist. And I don't get these warnings btw.
In my case, I can create SingleCycle animation, but no other, the window is disappearing after trying to choose the Type of animation.

Everything is okay here:
![image](https://github.com/no-slopes/sprite-animations/assets/38746516/7c3c82c2-50b8-413e-a349-38faa9b2e741)
Trying to change the Type of animation:
![image](https://github.com/no-slopes/sprite-animations/assets/38746516/28ccba4a-ccee-4d4e-8f6b-0eddbe89bae0)
And after clicking on this "Windrose" label:
![image](https://github.com/no-slopes/sprite-animations/assets/38746516/b548f8a8-968f-4843-a65a-7a1ed36308ec)

Tested in a new empty project with minimal implementation, with plugin version 2.3.3 and 2.3.0, still the same:
![image](https://github.com/no-slopes/sprite-animations/assets/38746516/4c15afcd-4101-40d2-993b-96c320943b15)

**Comment by indiegabo** [comment]
Looking into it right now. Thanks for the effort put into this. 

I has to do with Unity condidering that when you click the Animation Type dropbox the window loses focus. Pretty weird and seems like a bug to me. 

As it appears, I'll have to create a workaround for this.

**Comment by indiegabo** [comment]
Hey @arttmptt !

Just pushed v2.3.4 into production. I fixed it removing the `OnLostFocus` routine for Unity 2023.2.

If the window is still open when click the "Create" button it will focus the already opened window. The window still closes automatically upon clicking the x button or creating the animation.

Hope this helps you!

I'll wait for your feedback on the usage so I can close the usage. Let me know if everything is ok!

**Comment by arttmptt** [comment]
@indiegabo yep, now it works fine, thank you!

Foremost, I should have been using Unity of LTS version, always have some issues with non LTS versions, but I want to use the newer version so badly eeeh

**Comment by indiegabo** [comment]
The 2023.2 version looks awesome indeed. But I never start serious projects on any non LTS software. 

Glad to hear it is working fine now.
